#Config File example
save_dir: /home/willer/nanodet_concat/tools/models
model:
  arch:
    name: GFL
    backbone:
      name: ShuffleNetV2
      model_size: 1.0x
      out_stages: [2,3,4]
      activation: ReLU
    fpn:
      name: PAN
      in_channels: [116, 232, 464]
      out_channels: 96
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 1 #Please fill in the number of categories (not include background category)
      input_channel: 96
      feat_channels: 96
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0

class_names: &class_names ['helmet']  #Please fill in the category names (not include background category)
data:
  train:
    name: xml_dataset
    class_names: *class_names
    img_path: /home/willer/yolov5-3.1/data/coco/images/train2017  #Please fill in train image path
    ann_path: /home/willer/yolov5-3.1/data/coco/labels/train2017_voc  #Please fill in train xml path
    #input_size: [[320,320], [384,384], [448,448], [512,512], [576,576], [640,640], [704,704], [768,768], [832,832], [896,896], [960,960], [1024,1024], [1088,1088], [1216,1216], [1280,1280]] #[w,h]
    input_size: [320, 320]
    keep_ratio: True
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.8, 1.2]
      saturation: [0.8, 1.2]
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
  val:
    name: xml_dataset
    class_names: *class_names
    img_path: /home/willer/yolov5-3.1/data/coco/images/val2017 #Please fill in val image path
    ann_path: /home/willer/yolov5-3.1/data/coco/labels/val2017_voc #Please fill in val xml path
    input_size: [320, 320] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
device:
  gpu_ids: [0]
  workers_per_gpu: 12
  batchsize_per_gpu: 4
schedule:
#  resume: /home/willer/nanodet/tools/shufflenetv2_x1-5666bf0f80.pth
  load_model: /home/willer/nanodet_concat/nanodet_m.pth
  optimizer:
    name: SGD
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 300
    ratio: 0.1
  total_epochs: 10
  lr_schedule:
    name: MultiStepLR
    milestones: [3,6,9]
    gamma: 0.1
  val_intervals: 1
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 10
